solutionConfig:
  executionSteps:
    -
      action: "install"
      path: "identity-server/default/carbon.super/user-stores/*"
    -
      action: "install"
      path: "identity-server/default/carbon.super/identity-providers/*"
    -
      action: "install"
      path: "identity-server/default/carbon.super/service-providers/*"