/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.1
 * Generated at: 2018-01-12 06:59:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<title>Lebens - Foods for you</title>\r\n");
      out.write("\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<meta name=\"keywords\" content=\"\">\r\n");
      out.write("\t<meta name=\"description\" content=\"\">\r\n");
      out.write("\t<!--\r\n");
      out.write("\r\n");
      out.write("    Template 2076 Zentro\r\n");
      out.write("\r\n");
      out.write("    http://www.tooplate.com/view/2076-zentro\r\n");
      out.write("\r\n");
      out.write("    -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/animate.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/nivo-lightbox.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/nivo_themes/default/default.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\t<link href='https://fonts.googleapis.com/css?family=Roboto:400,500' rel='stylesheet' type='text/css'>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- preloader section -->\r\n");
      out.write("<section class=\"preloader\">\r\n");
      out.write("\t<div class=\"sk-spinner sk-spinner-pulse\"></div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- navigation section -->\r\n");
      out.write("<section class=\"navbar navbar-default navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<button class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("\t\t\t\t<span class=\"icon icon-bar\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"icon icon-bar\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"icon icon-bar\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"navbar-brand\">LEBENS</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t<li><a href=\"#home\" class=\"smoothScroll\">HOME</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#gallery\" class=\"smoothScroll\">FOOD GALLERY</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#menu\" class=\"smoothScroll\">SPECIAL MENU</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#contact\" class=\"smoothScroll\">RESERVE </a></li>\r\n");
      out.write("\t\t\t\t<li class=\"user-profile dropdown\">\r\n");
      out.write("\t\t\t\t<li class=\"smoothScroll\">\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.getContextPath()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/oidcsso\"  role=\"button\"\r\n");
      out.write("\t\t\t\t\t   aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAD0klEQVRIS41WbWxTZRR+zvt2GQ6FMfE7wuyMygoRzCRi1AQxaKKszQTstrYiQY1GnGu7pTqNQSdmY60iMQ74oevqYMO4dfuBgTl+uIyYGUTn9kOnMAjyQ2GKm5tb73vMbdNlu7fteH81fc45z/M+55x7LyHDcTxbVcBKc4JoPTRl0yCuj4cL/CkJQ1DoUUSHupobzqQrQ6mAp8sqrTEp6wEuAZAyZlYeE+gLyFh1x2cfnjXWMyXbXV6PImoUwDWZbmfCFP9LEi92hEOR2dgcArvHFwDjfWNyQf5tKC15HCvvKYC0SPw8PIK2aDd+GPzFrIG5KhoJNSSBGQJdOYiajBlFq1cg8Oo2WCxyDsTMOBBux9Gv+0wkzHB1RoKf60CcQPd8SoqfjLbkLr4OH9dVY2FOareUUvC+9QHOnr9oIFHjUhO2L1uCI3ECu6vyCEhsNkp5xvEYSkueyNiKE7392Hug1dwSoLWrOeikxCgq3UxTw3fXvIzCu60ZCS6P/o3tFe+mimGSmpXsbm8NQLXGiKV5udi725fWntnx2yveweXRK2YSwutk9/i6wdhgRB9Ztxrel1xXNan1+5rQ1z9giiXgONnLKy9CiJuN6LU52dgfenPeG/wzNo4XvLWYmJw2i1G4QE+V+6akQFYqqQ/db4N/53MZb9HU0oH2r3pTxiioqYwEREDjngBuunFpygITE5PYUbEL46nUA0gQuH2/S+CWdDJtdy1Dbc1OkM5mOB81RtDTdzr9DXWL0jU5mcVKYat9Pcq3bJpTqOvoCRyMRCGkJT0B8zGyu3xvgPBeJqOrX3HjwbX3zgn55uQpBD9pyTxlTAHa5PbfIcC/plo0/fnjdGzE5mLTFMcLt0WPo7WjG5qmmTdZKZXFwho31uH2tzF4i/5bSoFVK+7E2vtsWFe0CktyF827ySe/G0D/90P4cWgY+vNJP0w41BkOliUItr2Wz9NiEIJy8pYswtv+HVh++61XtWTJoDMjF7Brz0H8dWUMChgTFi6Mfho6PzMaDo/XxUzNegIhBqd9I+xPbsCCBdkZiSYm/0N71zEciXaDRWKdGFTa2dxwOFFr1in2+KuIuV7/S2kxZGcRHn5gDYrWrIQ1fxny8hZDCIFLl0Yx/Ns59J8aQO+3pzEV45lpYmJfZzgUSpY1DXexy1dOpO0H5MK4GqVB02JQSgMUJyQRQQgLpLSAhIjX0nRbQM8nlacl0IGSMt/yaYk6AWyd76WvlFIkRSvDEugK150z+pnxiyHefCWdxHiUFQqVUDfoBYQSf4B4EBA9UvFh/c2VrlH/A6ZBZa5n7W6uAAAAAElFTkSuQmCC\">Login <span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- home section -->\r\n");
      out.write("<section id=\"home\" class=\"parallax-section\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12 col-sm-12\">\r\n");
      out.write("\t\t\t\t<h1>LEBENS RESTAURANT</h1>\r\n");
      out.write("\t\t\t\t<h2>Reserve your table TODAY</h2>\r\n");
      out.write("\t\t\t\t<a href=\"#gallery\" class=\"smoothScroll btn btn-default\">LEARN MORE</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- gallery section -->\r\n");
      out.write("<section id=\"gallery\" class=\"parallax-section\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-offset-2 col-md-8 col-sm-12 text-center\">\r\n");
      out.write("\t\t\t\t<h1 class=\"heading\">Food Gallery</h1>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-4 col-sm-4 wow fadeInUp\" data-wow-delay=\"0.3s\">\r\n");
      out.write("\t\t\t\t<a href=\"images/gallery-img1.jpg\" data-lightbox-gallery=\"zenda-gallery\"><img src=\"images/gallery-img1.jpg\" alt=\"gallery img\"></a>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<h3>Lemon-Rosemary Prawn</h3>\r\n");
      out.write("\t\t\t\t\t<span>Seafood / Shrimp / Lemon</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<a href=\"images/gallery-img2.jpg\" data-lightbox-gallery=\"zenda-gallery\"><img src=\"images/gallery-img2.jpg\" alt=\"gallery img\"></a>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<h3>Lemon-Rosemary Vegetables</h3>\r\n");
      out.write("\t\t\t\t\t<span>Tomato / Rosemary / Lemon</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-4 col-sm-4 wow fadeInUp\" data-wow-delay=\"0.6s\">\r\n");
      out.write("\t\t\t\t<a href=\"images/gallery-img3.jpg\" data-lightbox-gallery=\"zenda-gallery\"><img src=\"images/gallery-img3.jpg\" alt=\"gallery img\"></a>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<h3>Lemon-Rosemary Bakery</h3>\r\n");
      out.write("\t\t\t\t\t<span>Bread / Rosemary / Orange</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-4 col-sm-4 wow fadeInUp\" data-wow-delay=\"0.9s\">\r\n");
      out.write("\t\t\t\t<a href=\"images/gallery-img4.jpg\" data-lightbox-gallery=\"zenda-gallery\"><img src=\"images/gallery-img4.jpg\" alt=\"gallery img\"></a>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<h3>Lemon-Rosemary Salad</h3>\r\n");
      out.write("\t\t\t\t\t<span>Chicken / Rosemary / Green</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<a href=\"images/gallery-img5.jpg\" data-lightbox-gallery=\"zenda-gallery\"><img src=\"images/gallery-img5.jpg\" alt=\"gallery img\"></a>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<h3>Lemon-Rosemary Pizza</h3>\r\n");
      out.write("\t\t\t\t\t<span>Pasta / Rosemary / Green</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- menu section -->\r\n");
      out.write("<section id=\"menu\" class=\"parallax-section\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-offset-2 col-md-8 col-sm-12 text-center\">\r\n");
      out.write("\t\t\t\t<h1 class=\"heading\">Special Menu</h1>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("\t\t\t\t<h4>Lemon-Rosemary Vegetable ................ <span>$20.50</span></h4>\r\n");
      out.write("\t\t\t\t<h5>Chicken / Rosemary / Lemon</h5>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("\t\t\t\t<h4>Lemon-Rosemary Meat ........................... <span>$30.50</span></h4>\r\n");
      out.write("\t\t\t\t<h5>Meat / Rosemary / Lemon</h5>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("\t\t\t\t<h4>Lemon-Rosemary Pork ........................ <span>$40.75</span></h4>\r\n");
      out.write("\t\t\t\t<h5>Pork / Tooplate / Lemon</h5>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("\t\t\t\t<h4>Orange-Rosemary Salad .......................... <span>$55.00</span></h4>\r\n");
      out.write("\t\t\t\t<h5>Salad / Rosemary / Orange</h5>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("\t\t\t\t<h4>Lemon-Rosemary Squid ...................... <span>$65.00</span></h4>\r\n");
      out.write("\t\t\t\t<h5>Squid / Rosemary / Lemon</h5>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("\t\t\t\t<h4>Orange-Rosemary Shrimp ........................ <span>$70.50</span></h4>\r\n");
      out.write("\t\t\t\t<h5>Shrimp / Rosemary / Orange</h5>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("\t\t\t\t<h4>Lemon-Rosemary Prawn ................... <span>$110.75</span></h4>\r\n");
      out.write("\t\t\t\t<h5>Chicken / Rosemary / Lemon</h5>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("\t\t\t\t<h4>Lemon-Rosemary Seafood ..................... <span>$220.50</span></h4>\r\n");
      out.write("\t\t\t\t<h5>Seafood / Rosemary / Lemon</h5>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- contact section -->\r\n");
      out.write("<section id=\"contact\" class=\"parallax-section\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-offset-1 col-md-10 col-sm-12 text-center\">\r\n");
      out.write("\t\t\t\t<h1 class=\"heading\">Reserve your table</h1>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-offset-1 col-md-10 col-sm-12 wow fadeIn\" data-wow-delay=\"0.9s\">\r\n");
      out.write("\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"name\" type=\"text\" class=\"form-control\" id=\"name\" placeholder=\"Name\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"email\" type=\"email\" class=\"form-control\" id=\"email\" placeholder=\"Email\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12 col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t<textarea name=\"message\" rows=\"8\" class=\"form-control\" id=\"message\" placeholder=\"Message\"></textarea>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-offset-3 col-md-6 col-sm-offset-3 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"submit\" type=\"submit\" class=\"form-control\" id=\"submit\" value=\"make a reservation\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-2 col-sm-1\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- footer section -->\r\n");
      out.write("<footer class=\"parallax-section\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-4 col-sm-4 wow fadeInUp\" data-wow-delay=\"0.6s\">\r\n");
      out.write("\t\t\t\t<h2 class=\"heading\">Contact Info.</h2>\r\n");
      out.write("\t\t\t\t<div class=\"ph\">\r\n");
      out.write("\t\t\t\t\t<p><i class=\"fa fa-phone\"></i> Phone</p>\r\n");
      out.write("\t\t\t\t\t<h4>090-080-0760</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"address\">\r\n");
      out.write("\t\t\t\t\t<p><i class=\"fa fa-map-marker\"></i> Our Location</p>\r\n");
      out.write("\t\t\t\t\t<h4>120 Duis aute irure, California, USA</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-4 col-sm-4 wow fadeInUp\" data-wow-delay=\"0.6s\">\r\n");
      out.write("\t\t\t\t<h2 class=\"heading\">Open Hours</h2>\r\n");
      out.write("\t\t\t\t<p>Sunday <span>10:30 AM - 10:00 PM</span></p>\r\n");
      out.write("\t\t\t\t<p>Mon-Fri <span>9:00 AM - 8:00 PM</span></p>\r\n");
      out.write("\t\t\t\t<p>Saturday <span>11:30 AM - 10:00 PM</span></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-4 col-sm-4 wow fadeInUp\" data-wow-delay=\"0.6s\">\r\n");
      out.write("\t\t\t\t<h2 class=\"heading\">Follow Us</h2>\r\n");
      out.write("\t\t\t\t<ul class=\"social-icon\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" class=\"fa fa-facebook wow bounceIn\" data-wow-delay=\"0.3s\"></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" class=\"fa fa-twitter wow bounceIn\" data-wow-delay=\"0.6s\"></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" class=\"fa fa-behance wow bounceIn\" data-wow-delay=\"0.9s\"></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" class=\"fa fa-dribbble wow bounceIn\" data-wow-delay=\"0.9s\"></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" class=\"fa fa-github wow bounceIn\" data-wow-delay=\"0.9s\"></a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- copyright section -->\r\n");
      out.write("<section id=\"copyright\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12 col-sm-12\">\r\n");
      out.write("\t\t\t\t<h3>LEBENS</h3>\r\n");
      out.write("\t\t\t\t<p>Powered by WSO2 Identity Server\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- JAVASCRIPT JS FILES -->\r\n");
      out.write("<script src=\"js/jquery.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"js/jquery.parallax.js\"></script>\r\n");
      out.write("<script src=\"js/smoothscroll.js\"></script>\r\n");
      out.write("<script src=\"js/nivo-lightbox.min.js\"></script>\r\n");
      out.write("<script src=\"js/wow.min.js\"></script>\r\n");
      out.write("<script src=\"js/custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
