solutionConfig:
  executionSteps:
    -
      action: "install"
      path: "identity-server/default/carbon.super/service-providers/*"
    -
      action: "install"
      path: "tomcat/default/webapps/lebens-legazy.com"
    -
      action: "install"
      path: "tomcat/default/webapps/francesca.com"
  deployerDependencies:
    -
      deployer: "tomcat/default/webapps/francesca.com"
      dependency: "identity-server/default/carbon.super/service-providers/sp2_saml.xml"
    -
      deployer: "tomcat/default/webapps/lebens-legazy.com"
      dependency: "identity-server/default/carbon.super/service-providers/sp1_oauth.xml"