solutionConfig:
  executionSteps:
    -
      action: "install"
      path: "identity-server/default/bar.com/user-stores/*"
    -
      action: "install"
      path: "identity-server/default/carbon.super/user-stores/*"
    -
      action: "install"
      path: "identity-server/default/carbon.super/service-providers/*"
    -
      action: "install"
      path: "identity-server/default/carbon.super/identity-providers/*"
    -
      action: "install"
      path: "tomcat/default/webapps/lebens.com"
  deployerDependencies:
    -
      deployer: "tomcat/default/webapps/lebens.com"
      dependency: "identity-server/default/carbon.super/service-providers/sp1_oauth.xml"